/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface MathTestInterface extends ethers.utils.Interface {
  functions: {
    "oneAsUint32()": FunctionFragment;
    "scaleDown(uint128)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "oneAsUint32",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "scaleDown",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "oneAsUint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "scaleDown", data: BytesLike): Result;

  events: {};
}

export class MathTest extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: MathTestInterface;

  functions: {
    oneAsUint32(overrides?: CallOverrides): Promise<[void]>;

    "oneAsUint32()"(overrides?: CallOverrides): Promise<[void]>;

    scaleDown(n: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>;

    "scaleDown(uint128)"(
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  oneAsUint32(overrides?: CallOverrides): Promise<void>;

  "oneAsUint32()"(overrides?: CallOverrides): Promise<void>;

  scaleDown(n: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

  "scaleDown(uint128)"(
    n: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    oneAsUint32(overrides?: CallOverrides): Promise<void>;

    "oneAsUint32()"(overrides?: CallOverrides): Promise<void>;

    scaleDown(n: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "scaleDown(uint128)"(
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    oneAsUint32(overrides?: CallOverrides): Promise<BigNumber>;

    "oneAsUint32()"(overrides?: CallOverrides): Promise<BigNumber>;

    scaleDown(n: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    "scaleDown(uint128)"(
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    oneAsUint32(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "oneAsUint32()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    scaleDown(
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "scaleDown(uint128)"(
      n: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
