/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import { Contract, ContractFactory, Overrides } from "@ethersproject/contracts";

import type { MathTest } from "../MathTest";

export class MathTest__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<MathTest> {
    return super.deploy(overrides || {}) as Promise<MathTest>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MathTest {
    return super.attach(address) as MathTest;
  }
  connect(signer: Signer): MathTest__factory {
    return super.connect(signer) as MathTest__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MathTest {
    return new Contract(address, _abi, signerOrProvider) as MathTest;
  }
}

const _abi = [
  {
    inputs: [],
    name: "oneAsUint32",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "n",
        type: "uint128",
      },
    ],
    name: "scaleDown",
    outputs: [
      {
        internalType: "uint128",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101fe806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063b9442f6a1461003b578063d883c91214610045575b600080fd5b6100436100ab565b005b6100836004803603602081101561005b57600080fd5b8101908080356fffffffffffffffffffffffffffffffff1690602001909291905050506100d9565b60405180826fffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b6100d76100c068056bc75e2d631000006100d9565b6fffffffffffffffffffffffffffffffff16610106565b565b6000670de0b6b3a7640000826fffffffffffffffffffffffffffffffff16816100fe57fe5b049050919050565b61019c81604051602401808281526020019150506040516020818303038152906040527ff5b1bba9000000000000000000000000000000000000000000000000000000007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19166020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff838183161783525050505061019f565b50565b60008151905060006a636f6e736f6c652e6c6f679050602083016000808483855afa505050505056fea26469706673582212200c455aa5df764dc3f7e6d11ada1a9c70dd2c7f7cd427685c43c14429eadd09a564736f6c63430007060033";
